### ISSUE TITLE
"Add DeployKey to GitHub from CircleCI" したけど ERROR: The key you are authenticating with has been marked as read only.

### ISSUE THREAD

**Issue by bakorer** [taichi/ci-yarn-upgrade#37]
## 相談内容

- [Adding read/write deployment key - CircleCI](https://circleci.com/docs/1.0/adding-read-write-deployment-key/)

の手順に沿って、Read/write key を設定したけど、引き続き以下のようなエラーが発生します。

Read/write key を設定するだけでは `ci-yarn-upgrade --execute` の内部で `git push` する処理で利用されないのでしょうか 🤔 ？

他に設定項目があれば教えていただきたいです 🙏 

**エラーメッセージ**

![image](https://user-images.githubusercontent.com/844012/32057497-6ba65f16-baa2-11e7-8930-056926b97995.png)

```
#!/bin/bash -eo pipefail
yarn global add ci-yarn-upgrade
export PATH="$PATH:`yarn global bin`"
ci-yarn-upgrade --execute
yarn global v1.0.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "ci-yarn-upgrade@0.4.9" with binaries:
      - ci-yarn-upgrade
Done in 3.29s.
{ error: '',
  errorcode: 128,
  stdout: '',
  stderr: 'ERROR: The key you are authenticating with has been marked as read only.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n' }
Exited with code 1
```

**現状の .circleci/config.yml**

```yml
  continuous_yarn_upgrade:
    working_directory: ~/continuous_yarn_upgrade

    branches:
      only:
        - master

    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - deploy:
          name: Continuous yarn upgrade
          command: |
            yarn global add ci-yarn-upgrade
            export PATH="$PATH:`yarn global bin`"
            ci-yarn-upgrade --execute
```

**Comment by bakorer** [comment]
@taichi すみません、完全に個人的な相談事項なのですが、もし宜しければ「この辺ちゃんと確認した？」とか、なんでも良いので、ご回答頂けると嬉しいです 🙏

**Comment by taichi** [comment]
CircleCIのプロジェクト毎の設定画面で環境変数は設定していますか？
![image](https://user-images.githubusercontent.com/66100/32062206-cbf72f38-baae-11e7-9aba-4f4c55f24996.png)

**Comment by taichi** [comment]
少なくともエラーメッセージを見る限り、CircleCIが使っているSSHの鍵が読み取り専用になっているようです。

**Comment by bakorer** [comment]
コメントありがとうございます 🙏 

> CircleCIのプロジェクト毎の設定画面で環境変数は設定していますか？

はい！設定しております ✅ 

![image](https://user-images.githubusercontent.com/844012/32106268-2068d0e6-bb66-11e7-99ac-cfe8d37d3400.png)

**Comment by bakorer** [comment]
> 少なくともエラーメッセージを見る限り、CircleCIが使っているSSHの鍵が読み取り専用になっているようです。

そうなんですね…。

SSH key なんですが、
https://circleci.com/gh/user/repo/edit#checkout
に設定されているのは Read only key で、

Read/write key の設定は、
https://circleci.com/gh/user/repo/edit#ssh
から設定するのであってますでしょうか？

また、GitHub Deploy keys https://github.com/user/repo/settings/keys は、
以下のように `Read only key` と `Read/write key` がそれぞれ設定されてますでしょうか 👀 ？

![image](https://user-images.githubusercontent.com/844012/32106507-dbc3d246-bb66-11e7-9963-23d96c3a67c0.png)

質問ばかりで恐縮ですが、お手すきのときでもコメントいただけると 🙏

**Comment by bakorer** [comment]
📝 追伸: `add_ssh_keys` を `.circleci/config.yml` に設定したら進捗ありました。

（けど、別のエラーが発生するようになりました… 😟 

```yml
      - add_ssh_keys:
          fingerprints:
            - "MY_FINGERPRINTS"
```

**エラーメッセージ**

![image](https://user-images.githubusercontent.com/844012/32107785-9ad23602-bb6a-11e7-9934-240ce23ed94e.png)

```
#!/bin/bash -eo pipefail
yarn global add ci-yarn-upgrade
export PATH="$PATH:`yarn global bin`"
ci-yarn-upgrade --execute
yarn global v1.0.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "ci-yarn-upgrade@0.4.9" with binaries:
      - ci-yarn-upgrade
Done in 3.07s.
{ error: '',
  errorcode: 129,
  stdout: '',
  stderr: 'error: Unknown subcommand: get-url\nusage: git remote [-v | --verbose]\n   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>\n   or: git remote rename <old> <new>\n   or: git remote remove <name>\n   or: git remote set-head <name> (-a | --auto | -d | --delete |<branch>)\n   or: git remote [-v | --verbose] show [-n] <name>\n   or: git remote prune [-n | --dry-run] <name>\n   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]\n   or: git remote set-branches [--add] <name> <branch>...\n   or: git remote set-url [--push] <name> <newurl> [<oldurl>]\n   or: git remote set-url --add <name> <newurl>\n   or: git remote set-url --delete <name> <url>\n\n    -v, --verbose         be verbose; must be placed before a subcommand\n\n' }
Exited with code 1
```
